on: workflow_dispatch
name: Deploy APIM Service (ARM)
jobs:
  arm-template-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
        template: ./IaC/azuredeploy-apim.json
        parameters: ./IaC/parameters-apim.json
